### ISSUE TITLE
[可決] 依頼募集範囲を誰でもOKにする

### ISSUE THREAD

**Issue by ken-ty** [flutteruniv/yoheiguild#10]
## 提案内容

依頼がないのでPJが回らないという問題の解決案。
開発メンバーがいても、依頼がないとこのPJは回らない。現状依頼が飛んできてないので、依頼募集の範囲を増やしてみる。

### 懸念

懸念としては、codeboyや質問zoomが受けられるプランへの加入の意義が薄れてしまうかもしれないこと。
ただし、こちらは開発者がやりたいと思ったことのみ着手するので、差別化はできている。
また、求人などはNG。以下に抵触する為。
https://github.com/flutteruniv/docs/blob/master/flutterwork.md
↓
共同開発の3ヶ月間だけとして、期間限定で個人からも募集してみる。
もし3ヶ月以上このPJをやるなら、個人開発と共同開発に依頼募集の範囲を減らしていくように調整すれば問題ないかと思う。

**Comment by ken-ty** [comment]
1月中に依頼が来ないなら、2月から施行します。
賛成、反対、そのほかご意見やアイデアありましたら是非↓に！

**Comment by kboy-silvergym** [comment]
今の依頼募集範囲はどうなっているんですか？

**Comment by ken-ty** [comment]
@kboy-silvergym 

今は 個人開発・共同開発 のみから受け付けています。

**Comment by kboy-silvergym** [comment]
なるほど。誰でもokにすると例えばどう言うのが追加しそうなイメージです？

**Comment by ken-ty** [comment]
はい、以下のようなものを想定しています。

- 質問ズームで対応している内容と同等の依頼
- Slack で 個人開発_xxx と公言していないもの、個人的に開発しているアプリについての依頼
- 技術イベントや記事作成のヘルプ依頼
- その他想定外からの依頼

ただし、投げた依頼を対応するかどうかは傭兵（開発者）次第なので、モラルに欠けたものは着手されずに残ると考えてます。

**Comment by kboy-silvergym** [comment]
>質問ズームで対応している内容と同等の依頼

これは確かにぶつかる可能性が気になりますが、一旦実験的にやってみても良いです！
その後、やはり問題だなと思ったら言います！

**Comment by ken-ty** [comment]
了解です！問題あったら教えてください！

依頼募集範囲を誰でもOKにする 2/1より施行します。

**Comment by ken-ty** [comment]
施行しましたので、 close します。
