### ISSUE TITLE
【基礎実装】通知機能実装

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/yoheiguild#11]
### マスト
- Android、iosともに通知を飛ばせるように設定する
- 時間を引数に入れることで通知が飛ぶようになる関数を作る

### できれば
- 同じ時間で曜日ごとに毎週繰り返すかの情報も引数にもつ
- 詳しいやり方を記事に書いて公開

## 依頼主について

[個人開発](https://www.figma.com/file/3iH4IrxIF7qOYFcd79J82d/%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=0%3A1&mode=design&t=kYX1ZJaaRETd4yDK-1)

## その他、注意点や要望・補足など

[GitHub](https://github.com/IkemotoNanako/repeat_notification_app.git)

---

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から1ヶ月 |
| 報酬(option) | たくさん褒める |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by susatthi** [comment]
@IkemotoNanako 

次のパッケージで進めても良いですか？

- riverpod + riverpod_generator
- freezed
- auto_route 

fvm 導入してよいでしょうか？

.vscode コミットしてよいでしょうか？

lint として pedantic_mono 導入してよいでしょうか？

**Comment by IkemotoNanako** [comment]
全部オッケーです！提案ありがとうございます！！

**Comment by susatthi** [comment]
@ken-ty 

本Issueと #12 を私にアサインをお願いします！権限がないようですー

![CleanShot 2024-01-20 at 06 40 17@2x](https://github.com/flutteruniv/yoheiguild/assets/13707135/ef2e7fb5-62e9-4a92-af38-d8ef1bef18bf)

**Comment by ken-ty** [comment]
@susatthi 
しました!
権限調整面倒なので、今後のアサイン追加も自分見つけ次第やります!

**Comment by ken-ty** [comment]
<img width="1026" alt="スクリーンショット 2024-04-01 13 12 06" src="https://github.com/flutteruniv/yoheiguild/assets/38717219/6ebf7f26-c694-4269-bffb-e3abab983504">

こちら見逃してました。 close します！
