### ISSUE TITLE
【基礎実装】shared_preferencesの実装

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/yoheiguild#12]
### マスト

- shared_preferencesの設定をする
- 保存の関数を作る
- 削除の関数を作る
- 変更の関数を作る

### できれば

- 時間、繰り返し設定、この時間を使うかのフラグ、アラームをかけるかのフラグ、通知を送るのかのフラグをいい感じに保存する方法を考える
- shared_preferencesの使い方を記事にして公開する

## 依頼主について

[個人開発](https://www.figma.com/file/3iH4IrxIF7qOYFcd79J82d/%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=0-1&mode=design&t=tGn70w8dviptCsTs-0)

## その他、注意点や要望・補足など

[GitHub](https://github.com/IkemotoNanako/repeat_notification_app.git)

---

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から1ヶ月|
| 報酬(option) | いっぱい褒める |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by susatthi** [comment]
やります！（Slackで報告済み）

**Comment by susatthi** [comment]
@ken-ty 

#11 と一緒にやったのでこちらはクローズしてほしいです！（私にクローズ権限が無い）

**Comment by ken-ty** [comment]
@susatthi 
了解です！対応お疲れ様でした。
