### ISSUE TITLE
【Flutter大学web】 go_router5系以上にしないとflutter3.1.0以上のbuild通らないけど、バージョンを上げると画面遷移の挙動が変わってしまう問題

### ISSUE THREAD

**Issue by kboy-silvergym** [flutteruniv/yoheiguild#13]
## 依頼内容

Flutter大学webアプリの以下のタスクを調査して、PRまで出してもらえたら最高です。改善案までだけでも大変ありがたいです！
https://github.com/flutteruniv/salon_app_web/issues/802

## 依頼主について

Flutter大学を運営するkboyです。

## その他、注意点や要望・補足など

特になし

---

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から1ヶ月。  |
| 報酬(option) | 500FUT |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by ken-ty** [comment]
プロジェクトが終了して一定期間が経過しましたので、closeします！
この課題に興味のある方は https://github.com/flutteruniv/salon_app_web/issues/802 をご参照ください。
