### ISSUE TITLE
【大規模クエスト】 誰もが使うFlutter学習ロードマップ兼問題集をFlutter大学が先導しよう

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/yoheiguild#15]
## 依頼内容
以下を作成する方針を立てる＆メンバー集め
- 学習ロードマップの作成
- 各スキルに対応する問題の作成
- 問題に対応するレビュー基準作成

[問題の例](https://github.com/yumemi-inc/flutter-training-template)
[レビュー表の例](https://notion.yumemi.co.jp/flutter%E7%A0%94%E4%BF%AE%E8%AA%B2%E9%A1%8C%E3%81%AE%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E8%A6%B3%E7%82%B9%E8%A1%A8)
## 依頼主について
ハンマー使いのみどりです
Flutter Lv 17 の初級です

## その他、注意点や要望・補足など
複数人募集です

## 背景
- 初学者から中級者を目指すとき、知る必要のある概念の名前すら知らないために学習方針を立てるのに困る現状がある
- Flutterの学習ロードマップは初学者が対象のものがほとんど

## どう回すか
- レビューが欲しい場合はFlutter大学の買い切り相談などに繋げる(定期収入になってWinWinだと思う？)
- 公開して会社も使って良いものにする(Flutter 大学、問題作成者の知名度アップ)

## 意気込み
我がクランはクラン発祥のロードマップが全てのクランで使わられる未来を夢みて！

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から1ヶ月。  |
| 報酬(option) |  |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by ken-ty** [comment]
@IkemotoNanako 
面白いタイトルですね！！
ロードマップというと、Flutter大学だと以下があります。
https://zenn.dev/flutteruniv_dev/articles/flutter-roadmap?redirected=1

学習ロードマップの作成 → Zenn の記事作成のイメージですか？
また、上記記事は初級、今回作成するロードマップは中級者向け、という感じでしょうか？

**Comment by ken-ty** [comment]
> レビューが欲しい場合はFlutter大学の買い切り相談などに繋げる(定期収入になってWinWinだと思う？)
> 公開して会社も使って良いものにする(Flutter 大学、問題作成者の知名度アップ)
> ...
> 我がクランはクラン発祥のロードマップが全てのクランで使わられる未来を夢みて！

有償キャッチアップ、ニーズありそうw。flutterエンジニアを増やすお手伝いは、夢がある！
似たところで、こんぶさんが Flutter 講師 やってましたね。 学校&会社の研修とかに繋げられるかも？？
→ Flutter 大学の人は格安で受けられる、みたいにするのもありか。
https://note.com/macgyverthink/n/nfbbbbda4cb4c

**Comment by IkemotoNanako** [comment]
> 学習ロードマップの作成 → Zenn の記事作成のイメージですか？

[ゆめみのFlutter研修](https://github.com/yumemi-inc/flutter-training-template)をイメージしていました！
ただし、Flutter大学に即した形に自分たちでも作ってみようという企画です〜！
Flutter大学の場合、教えてくださったように初学者向けの資料は揃ってるようなので、中級者を目指す人向けを考えてみました！

**Comment by IkemotoNanako** [comment]
> 似たところで、こんぶさんが Flutter 講師 やってましたね。 学校&会社の研修とかに繋げられるかも？？

こんぶさん先生だったんですね！学校&会社の研修につながって欲しいです！拙い文章から私の意図を汲み取ってくださってありがとうございます！！！ゆめみのコードチェックが全会社で使えるように公開されているのを意識してます！

> → Flutter 大学の人は格安で受けられる、みたいにするのもありか。
FUTが使えたりすると良さそうですね！格安でもレビューしてくださる方がいるとありがたいのですが、極力WinWinにしたいですー！

**Comment by ken-ty** [comment]
> > 学習ロードマップの作成 → Zenn の記事作成のイメージですか？
> 
> [ゆめみのFlutter研修](https://github.com/yumemi-inc/flutter-engineer-codecheck)をイメージしていました！ ただし、Flutter大学に即した形に自分たちでも作ってみようという企画です〜！ Flutter大学の場合、教えてくださったように初学者向けの資料は揃ってるようなので、中級者を目指す人向けを考えてみました！

なるほどです！であれば flutteruniv/xxxx と研修用のpublicリポジトリ作っちゃうのが良さそうっすね！
確かに共同開発ぽい笑

ガッツリ関わるお時間はなさそうなのですが、アイデア出しなどはお力になりたいですね！
「以下を作成する方針を立てる」部分に参加希望です笑

kboyさんに相談してみるところからですかね？？

**Comment by ken-ty** [comment]
yoheyguild のもくもく会とかでも是非会話しましょう👍
いろんな人の意見聞けそう

**Comment by IkemotoNanako** [comment]
共同開発っぽいですよね笑
アイデア出し期待してます〜〜〜！
方針立てがんんばりましょー！
Kboyさんに相談すべきですよね。。。
ただ、正直私の実力（やる気込み）だと作る側より使う側なんで強い傭兵を求めてます。。。
もくもく会で話しますーー！木曜日！！

**Comment by IkemotoNanako** [comment]
今は、２つの案があります！
- [ゆめみの研修](https://github.com/yumemi-inc/flutter-training-template)のようにGitHubでセッションをこなしながら１つのアプリを作る
- [ゆめみの研修](https://github.com/yumemi-inc/flutter-training-template)がカバーしていない分野を１セッション１動くものになる構成で問題を作っていく（どこからでもできる形で流れはないからとっかかりやすい）

２つのアイデアもあります！
- WebアプリにしてProgateみたいに問題を解いてキャラをレベルアップさせる
- 1セッションにつき1記事も作る

**Comment by IkemotoNanako** [comment]
すささんの記事でcloseします！
https://zenn.dev/susatthi/articles/20240309-111704-flutter-firebase-app
