### ISSUE TITLE
【MyGourmet】地図上に写真をピンで表示して欲しいです

### ISSUE THREAD

**Issue by schwarzwald0906** [flutteruniv/yoheiguild#22]
### 依頼主について

共同開発15 MyGourmetのリーダーの金です。

### 依頼内容

Flutter側の人手が足りていないので、可能であれば手伝っていただきたいです。
特に、写真を地図上に表示する機能を実装して欲しいです。
※UIを修正するといった初心者の方向けのタスクもあるので、上記にこだわらず、応募していただけたらと思います。

【実装概要】
firestoreに、GCSに保存した写真のパスと、写真の位置情報を、保存しております。
そこから写真を取得して、地図上に表示する機能を実装して欲しいです。
可能であれば、写真をタップしたら拡大して表示させたり、写真に付加された情報を表示できるようにもしていただきたいです。
ライブラリは、料金面を鑑みて、flutter_mapかmapbox_maps_flutterで考えています。

・デザインはこちらです
https://www.figma.com/file/9qlPzlsvF9CfYiYBED4yNR/My_Gourmet?type=design&node-id=0%3A1&mode=design&t=AszYEXQ00hetbQKo-1

### その他、注意点や要望・補足など

木曜日21時からMTGです。日曜日の9時〜12時にももくもく会をやっています。
可能であれば木曜日は出ていただきたいです。日程は要望があれば調整します。
日曜日でも構いません。
上記の機能は、3月末の発表会にのせるので、そこまでに実装していただけるとありがたいです。

### Expire(一定期間を指定)

依頼日から1ヶ月。

### 報酬(option)

1000FUT or アプリの今後1年間で発生する収益の5％

### 対応内容を記事などで公開しても良いか

はい

### 記事でプロジェクトについて言及しても良いか

はい

**Comment by ken-ty** [comment]
こちらチーム内で解決したとのことなので、close します！！
頑張ってください！
