### ISSUE TITLE
課金･広告を実装する

### ISSUE THREAD

**Issue by dongri727** [flutteruniv/yoheiguild#7]
## 依頼内容

Flutter Webでサブスクリプション・広告表示をする方法
 - 提案　具体的にどんな方法が可能か提案してください。
 - 実装　実際にコードを書いてください 
 - 現状　E-mail認証でsign up･signin
 - 希望　以下の３Routeに分ける。どれか一つのRouteだけ考えていただければいいです。
    - A  月１ドルでサブスクリプション
    - B  E-mail認証はするけど無料、そのかわりaccount_pageにバナー広告が入る、広告非表示のためにサブスクリプションにUGできる。
    - C 認証なしでゲストLogin　ログインするときに30秒程度の広告が挟まる 広告を見たらindex.dartに入る、UserID 0になる。

https://github.com/dongri727/acorn/tree/main
対象となるのは　acorn_flutter →　lib →　users

## 依頼主について

Flutter大学での個人開発　依頼主は還暦過ぎて一念発起、個人開発を始めたアマチュア

## その他、注意点や要望・補足など

 Serverpodを使っている、まだbackendがlocalにしかないので、やりにくいことが多いと思いますが、よろしくお願いします

---

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から3ヶ月。  |
| 報酬(option) | 上記３Routeのいずれについても提案1000FUT、実装3000FUT |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by dongri727** [comment]
書き方を間違えたらしい･･･みんな消えてしまった。

**Comment by dongri727** [comment]
依頼内容
Flutter Webでサブスクリプション・広告表示をする方法
　提案　具体的にどんな方法が可能か提案してください。
　実装　実際にコードを書いてください 

現状　E-mail認証でsign up･signin

希望　以下の３Routeに分ける
　A  月１ドルでサブスクリプション
　B  E-mail認証はするけど無料、そのかわりaccount_pageにバナー広告が入る、広告非表示のためにサブスクリプションにUGできる。
　C 認証なしでゲストLogin　ログインするときに30秒程度の広告が挟まる 広告を見たらindex.dartに入る、UserID 0になる。

どれか一つのRouteだけ考えていただければいいです。


依頼主について
Flutter大学での個人開発　依頼主は還暦過ぎて一念発起、個人開発を始めたアマチュア　

補足
serverpodを使っている、まだbackendがlocalにしかないので、やりにくいことが多いと思いますが、よろしくお願いします

報酬
各Routeごとに　提案は1000FUT、実装は3000FUT

**Comment by ken-ty** [comment]
> 書き方を間違えたらしい･･･みんな消えてしまった。

`<!--` と `-->` で囲んだ範囲がコメントアウトされちゃってましたので、修正しました！

**Comment by dongri727** [comment]
オオ、ありがとうございます。

**Comment by ken-ty** [comment]
こちら、興味を持つ傭兵さんもいるものの、1つの依頼としては粒度が大きく
手が出しにくい状況ぽいです。

@dongri727 さんさえ良ければ、@ken-ty が複数の依頼に分割しますが、どうでしょう？

**Comment by dongri727** [comment]
お願いします。どれだけ細かくなっても構いません笑

**Comment by ken-ty** [comment]
@dongri727 
承知しました！

https://github.com/dongri727/acorn/tree/main
この依頼って、上記 project に課金・広告を実装したいって感じですよね？
project がどんなものかよく分からなかったので、ざっくり教えてもらうか、
acorn の README に概要記載お願いします！
例: https://github.com/flutteruniv/yoheiguild/blob/main/README.md

その方が傭兵のモチベも上がりそうっす。

**Comment by ken-ty** [comment]
3つの issue に分割しました。こちら重複になりますので、 close します。
この依頼に興味のある方は、分割した issue をご確認ください。
