### ISSUE TITLE
【withTone】カメラ機能を追加して、動画を Firebase_cloud にアップする

### ISSUE THREAD

**Issue by ken-ty** [flutteruniv/yoheiguild#8]
## 依頼内容

共同開発14_withTone 様にご協力頂き、タスクサンプルとして1つ依頼を頂きましたので、@ken-ty が代筆致します。

現在、楽器の演奏方法などを投稿できる機能を開発中です。
以下のデザインにそって、投稿画面のUIはおおよそできております。

<img width="863" alt="スクリーンショット 2023-10-01 19 47 01" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/46989cf9-6b88-47f4-9744-33792883d6ed">

やって頂きたい内容は以下になります。

-  ios, android 対応のカメラ機能を追加
  - 動画を撮影できるようにする
  - 撮影データは投稿画面でプレビューでき、投稿ボタン押下で firebase_cloud 上にアップロードされる
  - ios, android 実機で共に動かせること
  - ios, android シミュレータで画面を開いてもエラー落ちしないこと( シミュレータなら、stub に差し替えるなど )

アルバムから動画を選択してアップロードする機能もありますが、そちらは未対応で問題ないです。
まずは撮影動画をアップロードできるところを目指してます。

環境構築やキャッチアップの対応も致します。アサイン決定後、 Figma や Firebase に招待します。
このタスクは withTone PJ では https://github.com/Mayumi-Nakabayashi/withTone/issues/160 として管理していますので、アサイン以降のやり取りはそちらでお願いします。            

## 依頼主について

共同開発14_withTone。 
withTone は音楽ソーシャル学習プラットフォームです。  
楽器を演奏する人々が自分にとって居心地の良いコミュニティが見つけられず、音楽を気軽に続けることができない、という課題があります。withTone は世界中の音楽仲間と簡単につながることができ、お互いに学び合いながら気軽に音楽を続けられるような環境を実現します。
現在は6名で活動しております。興味のある方は是非メンバーにお声がけください。

## その他、注意点や要望・補足など

アサイン後、進捗は確認したいです。
毎週木曜22:00 の定例にて確認 もしくは 週一で進捗を Slack してください。
早めに PR を作成し、WIP で進行状態がわかるように進行いただくとありがたいです。

---

### 詳細設定

| 設定項目 | 設定値 |
| --- | --- |
| Expire(一定期間を指定) | 依頼日から1ヶ月。  |
| 報酬(option) |  |
| 対応内容を記事などで公開しても良いか(はい\|いいえ) | はい |
| 記事でプロジェクトについて言及しても良いか(はい\|いいえ) | はい |

**Comment by ken-ty** [comment]
環境構築は対応済（元々withToneに参加していた為）。
ここのコメントとか残しておくと、振り返りや記事を書くときの素材にできそう。

**Comment by ken-ty** [comment]
ios なんか上手く動かない。
一旦カメラ機能導入として、画像を撮影してみる。
android 実機で上手くいきそう。

**Comment by ken-ty** [comment]
PR を WIP で作成。
https://github.com/Mayumi-Nakabayashi/withTone/pull/163

**Comment by ken-ty** [comment]
参考にした記事: https://qiita.com/pikatyu3/items/fedfa27ab889b0d07b37

**Comment by asriel-dev-apps** [comment]
> ios なんか上手く動かない。
> 
> 一旦カメラ機能導入として、画像を撮影してみる。
> 
> android 実機で上手くいきそう。

iosは実機？？
simulatorだったらカメラ機能使えないと思われ

**Comment by ken-ty** [comment]
https://github.com/Mayumi-Nakabayashi/withTone/pull/163 でやったところまでマージ済み。
残対応中。

**Comment by ken-ty** [comment]
引き続き対応していきますが、withTone の方で進めていきたいと思います。
こちらの issue は close します！
